name: Run All Roaming Scripts

on:
  workflow_dispatch:          # allows manual trigger
  schedule:
    - cron: '45 14 * * *'     # runs daily at 10:45 AM ET (14:45 UTC)

permissions:
  contents: write             # required to commit changes to the repo

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run get_roaming_data_fast.py
      run: |
        python Scripts/get_roaming_data_fast.py

    - name: Run aggregate_roaming_data.py
      run: |
        python Scripts/aggregate_roaming_data.py

    - name: Run merge_with_vintage.py
      run: |
        python Scripts/merge_with_vintage.py

    - name: Run calculate_manufacturers_and_samples.py
      run: |
        python Scripts/calculate_manufacturers_and_samples.py

    - name: Run aggregate_critical_roaming_minutes.py
      run: |
        python Scripts/aggregate_critical_roaming_minutes.py

    - name: Set up Chrome and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip xvfb libxi6 libgconf-2-4 libnss3 libasound2 fonts-liberation libappindicator1 xdg-utils
        sudo apt-get install -y chromium-browser
        wget https://storage.googleapis.com/chrome-for-testing-public/122.0.6261.129/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver 
    
    - name: Run get_latest_intel_driver.py
      run: |
        python Scripts/get_latest_intel_driver.py

    - name: Set up Git identity
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
    
    - name: Commit and push complete set of files
      run: |
        git add History/*.csv
        git add Output/*.csv Output/*.json
        git commit -m "📊 Add daily, aggregated, merged, and manufacturer stats for $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push
    
