name: Run All Roaming Scripts

on:
  workflow_dispatch:          # allows manual trigger
  schedule:
    - cron: '45 14 * * *'     # runs daily at 10:45 AM ET (14:45 UTC)

permissions:
  contents: write             # required to commit changes to the repo

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run get_roaming_data_fast.py
      run: |
        python Scripts/get_roaming_data_fast.py

    - name: Run aggregate_roaming_data.py
      run: |
        python Scripts/aggregate_roaming_data.py

    - name: Run merge_with_vintage.py
      run: |
        python Scripts/merge_with_vintage.py

    - name: Run calculate_manufacturers_and_samples.py
      run: |
        python Scripts/calculate_manufacturers_and_samples.py

    - name: Run aggregate_critical_roaming_minutes.py
      run: |
        python Scripts/aggregate_critical_roaming_minutes.py

    - name: Set up Chromium and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/local/bin/chromedriver

    
    - name: Run get_latest_intel_driver.py
      run: |
        python Scripts/get_latest_intel_driver.py

    - name: Set up Git identity
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
    
    - name: Commit and push complete set of files
      run: |
        git add History/*.csv
        git add Output/*.csv Output/*.json
        git commit -m "📊 Add daily, aggregated, merged, and manufacturer stats for $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push

    - name: Copy data.json to wi-fi-adapter-search
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'Output/data.json'
        destination_repo: 'ecamulli/wi-fi-adapter-search'
        destination_folder: 'data'
        user_email: 'eric.camulli@7signal.com'
        user_name: 'ecamulli'
        commit_message: 'Automated update of data.json from roaming repo'

